ETSWORK-11483 - Storyshots can now be run against a local running instance of storybook.
Workgrid/workgrid-ui-components pull request #15
Opened 2021-07-21 19:09 UTC by coreyjv

This changes improves the development workflow by allowing the execution of storyshots tests against a locally running version of Storybook. In a CI environment storyshots are run against a built version of Storybook.

2021-07-21 19:52 UTC, TuckerWhitehouse requested changes
Guessing that trailing g is why the build is failing

2021-07-21 19:52 UTC, TuckerWhitehouse commented on src/storyshots/commonConfig.ts
> +g
?

2021-07-21 19:52 UTC, TuckerWhitehouse commented on src/storyshots/commonConfig.ts
> +  }
Does including this option not break axe (just silently ignores I'm guessing?)

2021-07-22 11:32 UTC, coreyjv commented on src/storyshots/commonConfig.ts
> +g
Accidental typo on my part. This has been fixed.

2021-07-22 11:33 UTC, coreyjv commented on src/storyshots/commonConfig.ts
> +  }
It's been a while since I committed this but I believe I was having issues with image snapshots when running against the local running version.

2021-07-22 12:33 UTC, TuckerWhitehouse approved these changes

2021-07-22 12:38 UTC, louise-hayes approved these changes

2021-07-22 13:06 UTC, stevetothdesign approved these changes

2021-07-22 13:08 UTC, merged