ETSWORK-9864 Add Input component
Workgrid/workgrid-ui-components pull request #7
Opened 2021-02-26 15:55 UTC by sjjharrington

This input component contains the very minimal functionality needed at this time to meet the use case. It provides the user with the ability to 

- create an input with a corresponding label, 
- supply events. 
- provide message during Invalid state

It takes advantage of the style-component lib.

2021-02-26 16:05 UTC, Kikketer submitted a review, later dismissed

2021-03-01 01:31 UTC, Kikketer approved these changes

2021-03-01 13:35 UTC, coreyjv requested changes

2021-03-01 16:10 UTC, Kikketer approved these changes

2021-03-01 18:49 UTC, stevetothdesign approved these changes

2021-03-02 16:08 UTC, coreyjv approved these changes
Nice work. Thanks!

2021-03-02 16:59 UTC, merged