ETSWORK-9967 - Add Sign In and No Network screens used for authentication
Workgrid/workgrid-ui-components pull request #8
Opened 2021-03-03 15:00 UTC by coreyjv

The `SignIn` component is used to allow customers to provide, change, and reset company code. It also provides a sign in button for the user to kick off the authentication process. For transparency due to browser constraints and the way authentication works we have to have a sign in button that a user clicks.

The `NetworkSplash` in a component that renders it's children if the network is available. It's meant to only be used in the authentication process per requirements. We will likely implement a different model for showing offline status when in the application in the future.

Other changes of note:

* Had to change TypeScript output to `ES2017` to align with Capacitor v3 targets
* Changed TypeScript configuration to output type definitions so it can be more easily consumed in the app
* Needed to change the build process so image assets are part of the module so they can be used in the app
* Added `@testing-library/jest-dom` to allow more simplified jest matchers
* Added ESLint plugins for `jest-dom` and `@testing-library/react` to enforce best practices

2021-03-03 15:23 UTC, stevetothdesign requested changes
Validate empty state and invalid company code on Check Company Code button press.

2021-03-03 15:25 UTC, sjjharrington commented
@coreyjv implemented changes look great. Do we need to add a test file for the NetworkSplash component?

2021-03-03 16:08 UTC, TuckerWhitehouse commented on src/components/Button.tsx
> +  type?: 'primary' | 'secondary' | 'tertiary' | 'success' | 'warning' | 'danger' | 'link'
Buttons already have a type (button or submit). Thoughts on using something like `variant` instead?

_I recognize this prop was not introduced here - just throwing out the option and if we want to consider it going forward in other areas._

2021-03-03 16:08 UTC, TuckerWhitehouse commented on src/import-svg.d.ts
> +}
Where did you steal this from? lol

2021-03-03 16:08 UTC, TuckerWhitehouse commented on src/components/SignIn.test.tsx
> +    pleaseEnterCompanyCodeText: '❗ Please enter a company code',
Do we have any broad guidelines for when we include a symbol in the translation vs hard-coded in the UI? Like would this value differ across languages 🤔

2021-03-03 16:11 UTC, Kikketer commented on src/components/SignIn.test.tsx
> +  }
Can you explain this?  Are we going to use i18next or anything?  Perhaps with the translation hooks so it doesn't have to get passed in as a prop?

2021-03-03 16:11 UTC, coreyjv commented on package.json
> +      "jest-dom/prefer-to-have-value": "off"
I turned it off because the auto-fix resulted in code that wouldn't pass tests because of Ionic web components. In my `SignIn` test alone there were three tests that were impacted. My assumption is that we'll have a lot of these as we add more screens with more inputs which is why I disabled it globally.

2021-03-03 16:14 UTC, coreyjv commented on src/components/SignIn.test.tsx
> +  }
As noted in the `README` for the project translations is out of scope for this library. Any displayable text must be provided as a prop to the component. We did not want to have the burden of managing translations in this library especially given that we'll be delivering this to many different platforms that may be a challenge to integrate with here.

2021-03-03 16:14 UTC, coreyjv commented on src/components/SignIn.tsx
> +    versionText?: string
Yes! There's no version on the web.

2021-03-03 16:16 UTC, coreyjv commented on src/components/SignIn.tsx
> +      <Button type={'primary'} onClick={() => onSignIn()}>
Is there an ESLint rule we can add to auto-fix this?

2021-03-03 16:17 UTC, Kikketer commented on src/components/SignIn.test.tsx
> +  }
Could we simulate the i18next hook?  I would hate to have a pile of props that we suddenly need to remove.  Something like `useTranslation` but hand rolled that just provides static text?
So then we just need to update one location when translations hit.

2021-03-03 16:18 UTC, coreyjv commented on src/components/Button.tsx
> +  type?: 'primary' | 'secondary' | 'tertiary' | 'success' | 'warning' | 'danger' | 'link'
I could go either way on this. I think the "language" used by UX is `type`

2021-03-03 16:19 UTC, coreyjv commented on src/components/SignIn.test.tsx
> +    pleaseEnterCompanyCodeText: '❗ Please enter a company code',
I don't think there are any guidelines yet. Since this is just a test the actual values for these don't matter. It'd be more appropriate to ask this in the App when we introduce the values there I think.

2021-03-03 16:20 UTC, coreyjv commented on src/components/SignIn.test.tsx
> +  }
Let's take this discussion offline.

2021-03-03 16:22 UTC, coreyjv commented on src/import-svg.d.ts
> +}
I honestly don't recall but if there's a better way to address this let me know!

2021-03-03 16:24 UTC, TuckerWhitehouse commented on src/components/Button.tsx
> +  type?: 'primary' | 'secondary' | 'tertiary' | 'success' | 'warning' | 'danger' | 'link'
Not sure if we'll ever have a scenario where we use a standard form with a submit button, but this would prevent that :(

2021-03-03 16:24 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +      <Button type={'primary'} onClick={() => onSignIn()}>
Great question. ha

2021-03-03 16:25 UTC, stevetothdesign commented
Possible add-on if quick or it can be a future enhancement would be to submit the form on hitting Return

2021-03-03 16:26 UTC, TuckerWhitehouse commented
> Possible add-on if quick or it can be a future enhancement would be to submit the form on hitting Return

@coreyjv This actually plays into my question about having a submit button - rather than listening for `onClick` on the button, could we listen to `onSubmit` on the form, and then we need `type=submit` for the button.

2021-03-03 16:39 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +      <Button type={'primary'} onClick={() => onSignIn()}>
https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-curly-brace-presence.md

2021-03-03 20:41 UTC, coreyjv commented on src/components/SignIn.tsx
> +  companyCode?: string
This will be fixed in my next commit. Thanks for the suggestion!

2021-03-03 20:42 UTC, coreyjv commented on src/components/SignIn.tsx
> +      <Button type={'primary'} onClick={() => onSignIn()}>
I'll include this ESLint rule plus the ESLint React plugin my next commit.

2021-03-03 20:42 UTC, coreyjv commented on src/components/Button.tsx
> +  type?: 'primary' | 'secondary' | 'tertiary' | 'success' | 'warning' | 'danger' | 'link'
This will be fixed in my next commit per our discussion.

2021-03-03 21:24 UTC, stevetothdesign submitted a review, later dismissed
Looks good!

2021-03-04 13:39 UTC, sjjharrington commented on .storybook/preview.js
> +  document.getElementsByTagName('html').item(0).classList.replace(classToRemove, context.globals.mode)
Whats the context for this?

2021-03-04 13:46 UTC, coreyjv commented on .storybook/preview.js
> +  document.getElementsByTagName('html').item(0).classList.replace(classToRemove, context.globals.mode)
I added a custom toolbar action in Storybook a while back to switch between "iOS" and "Android / Desktop" modes. It largely worked but the font switching wasn't working as expected. So the solution is to toggle the correct CSS classes to trigger the correct font families to be used.

2021-03-04 13:54 UTC, sjjharrington submitted a review, later dismissed

2021-03-04 14:10 UTC, TuckerWhitehouse commented on package.json
> +        2,
Nit - I find the strings easier to read than the numbers :)
```suggestion
        "error",
```

2021-03-04 14:10 UTC, TuckerWhitehouse commented on package.json
> +    "resetMocks": true
😀

2021-03-04 14:10 UTC, TuckerWhitehouse commented on src/components/Input.test.tsx
> +    expect(screen.getByTestId('ion-item')).toHaveClass('ion-invalid ion-touched', { exact: true })
Was this auto-fixed by something or did you just manually tweak these?

2021-03-04 14:10 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +  companyCodeIsValid: boolean
I think my comment may have gotten lost from before: This property seems to behave more like a controlled component, while the rest of the state is managed internally, and the `onCompanyCodeChange` method below seems to indicate it's pretty much only used for this.

Would a single `isCompanyCodeValid` parameter maybe be more clear & concise here?
```
isCompanyCodeValid: (companyCode: string) => boolean
```

2021-03-04 14:10 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +)
Nit: Could probably just inline this on line 128

2021-03-04 14:10 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +  const [isInvalid, setInvalid] = useState(!companyCodeIsValid)
If we replace this with an `isCompanyCodeValid` callback the problem goes away, but I think this won't work if the value of `companyCodeIsValid` is changed (`useState` takes an initial value only, we'd need a useEffect to overwrite it if the prop changed)
```js
useEffect(() => {
  setInvalid(!companyCodeIsValid)
}, [companyCodeIsValid])
```

2021-03-04 14:10 UTC, TuckerWhitehouse commented on src/import-svg.d.ts
> +}
Just didn't look like something we'd have hand-rolled cause I'm not even really sure what it does :D

2021-03-04 14:13 UTC, coreyjv commented on src/components/Input.test.tsx
> +    expect(screen.getByTestId('ion-item')).toHaveClass('ion-invalid ion-touched', { exact: true })
Auto-fixed!

2021-03-04 14:16 UTC, coreyjv commented on src/components/SignIn.tsx
> +)
It's used in two spots which is why I extracted it.

2021-03-04 14:28 UTC, Kikketer commented on src/components/Commenter.tsx
> +          <IonText color="medium" className="ion-padding-start">
Adding this to my list of "it's not enforced via code and won't break anything, but it's the pattern we've decided on"

2021-03-04 14:30 UTC, coreyjv commented on src/components/Commenter.tsx
> +          <IonText color="medium" className="ion-padding-start">
I don't think there's a need to add it to any list. It is enforced as are many rules ESLint rules that we have in place.

2021-03-04 14:31 UTC, Kikketer commented on src/components/NetworkSplash.tsx
> +        <CenteredContent tabIndex={0}>
Read up on the comment, we only will need to use the tabIndex=0 hack when there's nothing that's actually focusable inside the scrollable element correct?  So if you can focus on something inside, we shouldn't need to do this (attempting to stop a splurge of "just put tabIndex=0 everywhere, not sure why but that's what I saw" situation)

Also with the trend of having the format look like `attribute="static-string"` vs `attribute={'static-string'}` would this also qualify for that format?
```
tabIndex="0"
```

2021-03-04 14:34 UTC, coreyjv commented on src/components/NetworkSplash.tsx
> +        <CenteredContent tabIndex={0}>
@Kikketer -- What change are you specifically looking for here?

2021-03-04 14:35 UTC, coreyjv commented on src/components/SignIn.tsx
> +  const [isInvalid, setInvalid] = useState(!companyCodeIsValid)
@TuckerWhitehouse and I chatted about this. This was actually the intent and not a bug. I've pushed a change that renames a couple of properties to more clearly indicate the intent.

2021-03-04 14:37 UTC, Kikketer commented on src/components/NetworkSplash.tsx
> +        <CenteredContent tabIndex={0}>
```
{/* tabIndex for accessibility: https://dequeuniversity.com/rules/axe/3.5/scrollable-region-focusable?application=axe-puppeteer */}
        <CenteredContent tabIndex={0}>
```
Having `tabIndex="0"` is standard html.  Thought that since we are moving to that look/feel/pattern, this would also do that.

Just had the question to make it clear when and when-not to use the `tabIndex` on components.

2021-03-04 14:42 UTC, coreyjv commented on src/components/NetworkSplash.tsx
> +        <CenteredContent tabIndex={0}>
Per the `@types/react` [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1769) `tabIndex` is a `number`. Changing it to a string causes TypeScript to fail compilation.

2021-03-04 14:45 UTC, Kikketer submitted a review, later dismissed

2021-03-04 14:54 UTC, coreyjv commented on src/components/SignIn.stories.tsx
> +}
That's a great question. UX can use Storybook to test this. If it's critical in certain cases we can create stories to support the need increasing confidence.

2021-03-04 17:05 UTC, sjjharrington approved these changes

2021-03-04 17:54 UTC, stevetothdesign approved these changes

2021-03-04 18:37 UTC, TuckerWhitehouse commented on src/components/SignIn.tsx
> +  companyCodeIsValid: boolean
Context here: https://github.com/Workgrid/workgrid-ui-components/pull/8#discussion_r587520341

2021-03-04 18:38 UTC, TuckerWhitehouse approved these changes

2021-03-05 15:31 UTC, stevetothdesign approved these changes

2021-03-05 16:03 UTC, Kikketer approved these changes

2021-03-05 17:51 UTC, TuckerWhitehouse approved these changes

2021-03-05 18:47 UTC, merged